USE [master]
GO

/****** Object:  Database [AddZakaz]    Script Date: 26.01.2024 9:31:26 ******/
DROP DATABASE [AddZakaz]
GO

/****** Object:  Database [AddZakaz]    Script Date: 26.01.2024 9:31:26 ******/
CREATE DATABASE [AddZakaz]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AddZakaz', FILENAME = N'C:\Users\Student\AddZakaz.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AddZakaz_log', FILENAME = N'C:\Users\Student\AddZakaz_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AddZakaz].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AddZakaz] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AddZakaz] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AddZakaz] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AddZakaz] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AddZakaz] SET ARITHABORT OFF 
GO

ALTER DATABASE [AddZakaz] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AddZakaz] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AddZakaz] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AddZakaz] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AddZakaz] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AddZakaz] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AddZakaz] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AddZakaz] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AddZakaz] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AddZakaz] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AddZakaz] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AddZakaz] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AddZakaz] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AddZakaz] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AddZakaz] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AddZakaz] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AddZakaz] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AddZakaz] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AddZakaz] SET  MULTI_USER 
GO

ALTER DATABASE [AddZakaz] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AddZakaz] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AddZakaz] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AddZakaz] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AddZakaz] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AddZakaz] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AddZakaz] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AddZakaz] SET  READ_WRITE 
GO

